Web/DavinoComputers.Web/Controllers/PcBuildsController.cs
namespace DavinoComputers.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using DavinoComputers.Services.CategoryServices;
    using DavinoComputers.Services.PcBuildsServices;
    using DavinoComputers.Services.ProductServices;
    using DavinoComputers.Web.ViewModels.PcBuildViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class PcBuildsController : BaseController
    {
        private readonly IPcBuildService pcbuildService;
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;

        public PcBuildsController(ICategoryService categoryService, IProductService productService, IPcBuildService pcbuildService)
        {
            this.categoryService = categoryService;
            this.productService = productService;
            this.pcbuildService = pcbuildService;
        }

        [Authorize(Roles = Common.GlobalConstants.AdministratorRoleName)]
        public IActionResult Add()
        {
            return this.View(new AddPcBuildFormModel
            {
                CpuProducts = this.pcbuildService.GetCpuProducts(),
                GpuProducts = this.pcbuildService.GetGpuProducts(),
                MotherBoardProducts = this.pcbuildService.GetMotherBoardProducts(),
                RamProducts = this.pcbuildService.GetRamProducts(),
                PowerSupplyProducts = this.pcbuildService.GetPowerSupplyProducts(),
                ComputerCasesProducts = this.pcbuildService.GetComputerCaseProducts(),
            });
        }

        [Authorize(Roles = Common.GlobalConstants.AdministratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> Add(AddPcBuildFormModel pcbuild)
        {
            // TODO Ifs
            if (!this.pcbuildService.GetCpuProducts().Any(p => p.Id == pcbuild.ProductCPU))
            {
                this.ModelState.AddModelError(nameof(pcbuild.ProductCPU), "This kind of product doesn't exist");
            }

            if (!this.ModelState.IsValid)
            {
                pcbuild.CpuProducts = this.pcbuildService.GetCpuProducts();
                return this.View(pcbuild);
            }

            await this.pcbuildService.CreatePcBuild(pcbuild);

            return this.Redirect("/");
        }

        public IActionResult All()
        {
            var listPcBuilds = new ListingPcBuildsViewModel
            {
                PcBuilds = this.pcbuildService.ListAllPcBuilds(),
            };
            return this.View(listPcBuilds);
        }

        [Authorize(Roles = Common.GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(int id)
        {
            var pcbuild = this.pcbuildService.GetPcBuildForm(id);
            if (pcbuild == null)
            {
                return this.NotFound();
            }

            return this.View(pcbuild);
        }

        [Authorize(Roles = Common.GlobalConstants.AdministratorRoleName)]
        [HttpPost]
        public IActionResult Edit(int id, AddPcBuildFormModel pcbuild)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(pcbuild);
            }

            this.pcbuildService.EditPcBuild(id, pcbuild);
            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult Details(int id)
        {
            var pcbuild = this.pcbuildService.GetPcBuildDetails(id);
            if (pcbuild == null)
            {
                return this.NotFound();
            }

            return this.View(pcbuild);
        }
    }
}

Web/DavinoComputers.Web/Controllers/ProductsController.cs
namespace DavinoComputers.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using DavinoComputers.Services.CategoryServices;
    using DavinoComputers.Services.ProductServices;
    using DavinoComputers.Web.ViewModels.ProductViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsController : BaseController
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;

        public ProductsController(IProductService productService, ICategoryService categoryService)
        {
            this.productService = productService;
            this.categoryService = categoryService;
        }

        public IActionResult All(ListingProductViewModel query)
        {
            const int itemsPerPage = 9;
            var productsResult = this.productService.ListAllProducts(query.SearchTerm, query.Brand, query.Category, query.SubCategory, query.PageNumber, itemsPerPage);

            query.ItemsPerPage = itemsPerPage;
            query.Products = productsResult.Products;
            query.ProductsCount = productsResult.ProductsCount;
            query.Brands = this.productService.GetBrands();
            query.Categories = this.categoryService.GetCategories();
            query.SubCategories = this.categoryService.GetSubCategories().Select(s => s.Name);
            return this.View(query);
        }

        public IActionResult Details(int id)
        {
            var product = this.productService.GetProducDetails(id);

            if (product == null)
            {
                return this.Redirect("/Products/All");
            }

            return this.View(product);
        }
    }
}

Web/DavinoComputers.Web/Controllers/ShoppingCartsController.cs
namespace DavinoComputers.Web.Controllers
{
    using DavinoComputers.Services.ShoppingCartServices;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static DavinoComputers.Web.WebConstants;

    [Authorize]
    public class ShoppingCartsController : BaseController
    {
        private readonly IShoppingCartService shoppingCartService;

        public ShoppingCartsController(IShoppingCartService shoppingCartService)
        {
            this.shoppingCartService = shoppingCartService;
        }

        public IActionResult Index()
        {
            var username = this.User.Identity.Name;
            var shoppingCart = this.shoppingCartService.GetMyShoppingCartProducts(username);
            if (shoppingCart == null)
            {
                return this.NotFound();
            }

            return this.View(shoppingCart);
        }

        public IActionResult AddProductToCart(int productId, string name)
        {
            var username = this.User.Identity.Name;
            var result = this.shoppingCartService.AddProduct(username, productId);
            if (result == "Cart doesnt exist" || result == null)
            {
                return this.NotFound();
            }

            if (result == "Cant duplicate products")
            {
                this.TempData[GlobalMessageKey] = $"{name} is already in your shopping cart!";
                return this.Redirect(this.Request.Headers["Referer"].ToString());
            }

            this.TempData[GlobalMessageKey] = $"{name} have been added successfully!";
            return this.Redirect(this.Request.Headers["Referer"].ToString());
        }

        public IActionResult AddPcBuildToCart(int pcbuildId, string name)
        {
            var username = this.User.Identity.Name;
            var result = this.shoppingCartService.AddPcBuild(username, pcbuildId);
            if (result == "Cart doesnt exist" || result == null)
            {
                return this.NotFound();
            }

            if (result == "Cant duplicate products")
            {
                return this.Redirect(this.Request.Headers["Referer"].ToString());
            }

            this.TempData[GlobalMessageKey] = $"{name} have been added successfully!";

            return this.Redirect(this.Request.Headers["Referer"].ToString());
        }

        public IActionResult EditProduct(int productId, int quantity)
        {
            var username = this.User.Identity.Name;
            this.shoppingCartService.EditProductQuantity(username, productId, quantity);
            return this.RedirectToAction(nameof(this.Index));
        }

        public IActionResult DeleteProduct(int productId)
        {
            var username = this.User.Identity.Name;
            var result = this.shoppingCartService.DeleteProductFromCart(username, productId);
            if (result == null)
            {
                return this.NotFound();
            }

            return this.Redirect(this.Request.Headers["Referer"].ToString());
        }

        public IActionResult DeletePcBuild(int pcbuildId)
        {
            var username = this.User.Identity.Name;
            var result = this.shoppingCartService.DeletePcBuildFromCart(username, pcbuildId);
            if (result == null)
            {
                return this.NotFound();
            }

            return this.Redirect(this.Request.Headers["Referer"].ToString());
        }
    }
}

Web/DavinoComputers.Web/Views/PcBuilds/Add.cshtml
@model AddPcBuildFormModel
@{
    this.ViewData["Title"] = "Add Pc Build";
}

<h1 class="text-center">Create New Pc Build</h1>
<partial name="_PcBuildFormPartial" model="@Model" />

@section Scripts { 
    <partial name="_ValidationScriptsPartial" />
}

Web/DavinoComputers.Web/Views/PcBuilds/All.cshtml
@model ListingPcBuildsViewModel
@{
    this.ViewData["Title"] = "All PcBuilds";
}

<div class="row">
    <a class="mr-2 ml-3" asp-controller="Home" asp-action="Index">Home</a>
    <p class="mr-2">></p>
    <a class="mr-2" asp-controller="PcBuilds" asp-action="All">PcBuilds</a>
</div>
<h1 class="text-center">All Pc Builds</h1>
<hr />

<div class="row">
    @foreach (var pcbuilds in Model.PcBuilds)
    {
        <div class="media col-md-6 col-lg-4 col-sm-6 mb-4">
            <img src="@pcbuilds.ImageUrl" class="mr-3 p-2 w-50 mx-auto">
            <div class="media-body align-text-top">
                <a href="/PcBuilds/Details?id=@pcbuilds.Id" class="mt-0 font-weight-bold" style="color:black">@pcbuilds.Name</a>
                @foreach (var product in pcbuilds.Products)
                {
                    <p><small class="text-muted"> - @product.Brand @product.Model</small></p>
                }
                <h5 class="border-bottom">@pcbuilds.Price BGN</h5>
                <a asp-area="" asp-controller="ShoppingCarts" asp-action="AddPcBuildToCart" asp-route-pcbuildId="@pcbuilds.Id" asp-route-name="@pcbuilds.Name" class="btn btn-primary btn-sm">Add to cart</a>
                @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                {
                    <a class="btn btn-warning btn-sm" asp-area="" asp-controller="PcBuilds" asp-action="Edit" asp-route-id="@pcbuilds.Id" button">Edit</a>
                    <a class="btn btn-danger btn-sm" asp-area="" asp-controller="PcBuilds" asp-action="Delete" asp-route-id="@pcbuilds.Id" role="button">Delete</a>
                }
            </div>
        </div>
    }
</div>

Web/DavinoComputers.Web/Views/PcBuilds/Details.cshtml
@model PcBuildDetailsModel

@{
    this.ViewData["Title"] = "Pc Build Details";
}

<div class="row">
    <a class="mr-2 ml-3" asp-controller="Home" asp-action="Index">Home</a>
    <p class="mr-2">></p>
    <a class="mr-2" asp-controller="PcBuilds" asp-action="All">PcBuilds</a>
    <p class="mr-2">></p>
    <a class="mr-2" asp-controller="PcBuilds" asp-action="Details" asp-route-id="@Model.Id">@Model.Name</a>
</div>

<div class="card mb-3">
    <img class="card-img-top w-50 mx-auto" src="@Model.ImageUrl" alt="@Model.Name">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Description</p>
        <div class="row mt-3">
            <h2 class="card-text border-bottom ml-3 mr-3">@Model.Price BGN</h2>
            <a asp-area="" asp-controller="ShoppingCarts" asp-action="AddPcBuildToCart" asp-route-pcbuildId="@Model.Id" asp-route-name="@Model.Name" class="btn btn-primary btn-sm">Add to cart</a>
        </div>
    </div>
</div>

<h1 class="text-left mt-5">
    <a id="btnName" class="btn btn-primary btn-lg" onclick="showElements()">Hide components ...</a>
</h1>

<div id="showComponents" class="table-responsive">
    <h1>Components :</h1>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Brand</th>
                <th scope="col">Model</th>
                <th scope="col">Available</th>
                <th scope="col">Price</th>
                <th scope="col">Image Url</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Products)
            {
                <tr>
                    <td>@product.Brand</td>
                    <td>@product.Model</td>
                    <td>@(product.IsAvailable == true ? "Yes" : "No")</td>
                    <td>@product.Price BGN</td>
                    <td><img class="img-thumbnail w-25 mx-auto" src="@product.ImageUrl" /></td>
                    <td><a class="btn btn-info" asp-controller="Products" asp-action="Details" asp-route-id="@product.Id" target="_blank">Details</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    function showElements() {
        let componentsElements = document.getElementById('showComponents');
        let showBtn = document.getElementById('btnName');

        if (componentsElements.style.display == 'none') {
            componentsElements.style.display = 'block';
            showBtn.textContent = 'Hide components';
        } else {
            componentsElements.style.display = 'none';
            showBtn.textContent = 'Show components ...';
        }
    }
</script>

Web/DavinoComputers.Web/Views/PcBuilds/Edit.cshtml
@{
    this.ViewData["Title"] = "Edit PcBuild";
}

<h1 class="text-center">Edit Pc Build</h1>
<partial name="_PcBuildFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Web/DavinoComputers.Web/Views/PcBuilds/_PcBuildFormPartial.cshtml
@model AddPcBuildFormModel

<div class="row">
    <div class="offset-md-3 col-md-6 col-sm-12">
        <form method="post">
           
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" id="exampleFormControlInput1" placeholder="Ryzen, I-7 and etc...">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" rows="3" placeholder="Type some info for the currnet product..."></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" id="exampleFormControlInput1" placeholder="Cash in BGN...">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsAvailable"></label>
                <input asp-for="IsAvailable" />
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" id="exampleFormControlInput1" placeholder="The shortest URL for the image..">
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCPU"></label>
                <select asp-for="ProductCPU" class="form-control">
                    @foreach (var product in Model.CpuProducts)
                    {
                        <option value="@product.Id">@product.Brand @product.Model</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ProductGPU"></label>
                <select asp-for="ProductGPU" class="form-control">
                    @foreach (var product in Model.GpuProducts)
                    {
                        <option value="@product.Id">@product.Brand @product.Model</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ProductMotherBoard"></label>
                <select asp-for="ProductMotherBoard" class="form-control">
                    @foreach (var product in Model.MotherBoardProducts)
                    {
                        <option value="@product.Id">@product.Brand @product.Model</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ProductRAM"></label>
                <select asp-for="ProductRAM" class="form-control">
                    @foreach (var product in Model.RamProducts)
                    {
                        <option value="@product.Id">@product.Brand @product.Model</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ProductPowerSupply"></label>
                <select asp-for="ProductPowerSupply" class="form-control">
                    @foreach (var product in Model.PowerSupplyProducts)
                    {
                        <option value="@product.Id">@product.Brand @product.Model</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ProductComputerCase"></label>
                <select asp-for="ProductComputerCase" class="form-control">
                    @foreach (var product in Model.ComputerCasesProducts)
                    {
                        <option value="@product.Id">@product.Brand @product.Model</option>
                    }
                </select>
            </div>
            <input type="submit" class="btn btn-success btn-lg" />
        </form>
    </div>
</div>